[workspace]
resolver = "2"
members = [
    "crates/beacon-core",
    "crates/beacon-client",
    "crates/beacon",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
authors = ["Drake Stapleton <aien@aienos.com>"]
repository = "https://github.com/aien-dev/open-humanity"
