[workspace]
resolver = "2"
members = [
    "crates/beacon-core",
    "crates/beacon-client",
    "crates/beacon",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"
authors = ["Drake Stapleton <drake.aien@proton.me>"]
repository = "https://github.com/aien-dev/open-humanity"
